import type { Post, TrackerData } from "./types";

/**
 * Sample content shaped like a real client's tracker, used only when
 * DASHBOARD_DEMO_MODE=true. No live Notion connection is involved: this is
 * for showing a prospective or new client what the dashboard looks like
 * before their tracker is connected.
 */
function post(p: Omit<Post, "notionUrl" | "gbpPostedDate"> & { gbp?: string | null }): Post {
  return {
    ...p,
    gbpPostedDate: p.gbp ?? null,
    notionUrl: "https://notion.so",
  };
}

export const DEMO_POSTS: Post[] = [
  post({
    id: "demo-1",
    title:
      "The Complete Guide to Professional Studio Headshots in the Kansas City Area",
    slug: "studio-headshots-kc-guide",
    dateWritten: "2026-03-10",
    topic: "studio headshots Kansas City area",
    city: "Olathe",
    pillar: "Studio Headshots Kansas City Area",
    role: "Pillar Page",
    status: "Published",
    wordCount: 2280,
    publishedUrl: "https://example.com/blog/studio-headshots-kc-guide",
    lastRefreshed: "2026-06-20",
    gbp: "2026-07-05",
  }),
  post({
    id: "demo-2",
    title: "What to wear for studio headshots in Olathe",
    slug: "studio-headshots-what-to-wear",
    dateWritten: "2026-03-24",
    topic: "what to wear studio headshots",
    city: "Olathe",
    pillar: "Studio Headshots Kansas City Area",
    role: "Cluster Post",
    status: "Published",
    wordCount: 780,
    publishedUrl: "https://example.com/blog/studio-headshots-what-to-wear",
    lastRefreshed: null,
    gbp: "2026-06-28",
  }),
  post({
    id: "demo-3",
    title: "Studio vs. on-location headshots: which one do you need",
    slug: "studio-vs-on-location-headshots",
    dateWritten: "2026-04-08",
    topic: "studio vs on-location headshots",
    city: "Overland Park",
    pillar: "Studio Headshots Kansas City Area",
    role: "Cluster Post",
    status: "Published",
    wordCount: 820,
    publishedUrl: "https://example.com/blog/studio-vs-on-location-headshots",
    lastRefreshed: null,
    gbp: "2026-06-14",
  }),
  post({
    id: "demo-4",
    title: "How often should you refresh your headshot",
    slug: "how-often-refresh-headshot",
    dateWritten: "2026-04-22",
    topic: "headshot refresh frequency",
    city: "Leawood",
    pillar: "Studio Headshots Kansas City Area",
    role: "Cluster Post",
    status: "Published",
    wordCount: 690,
    publishedUrl: "https://example.com/blog/how-often-refresh-headshot",
    lastRefreshed: null,
  }),
  post({
    id: "demo-5",
    title: "LinkedIn profile photos that actually get replies",
    slug: "linkedin-profile-photos",
    dateWritten: "2026-05-04",
    topic: "linkedin profile photo Kansas City",
    city: "Olathe",
    pillar: "Personal Branding Photography Kansas City",
    role: "Cluster Post",
    status: "Published",
    wordCount: 730,
    publishedUrl: "https://example.com/blog/linkedin-profile-photos",
    lastRefreshed: null,
    gbp: "2026-06-21",
  }),
  post({
    id: "demo-6",
    title: "Personal brand photos for realtors in Leawood",
    slug: "realtor-personal-brand-photos",
    dateWritten: "2026-05-19",
    topic: "realtor branding photos",
    city: "Leawood",
    pillar: "Personal Branding Photography Kansas City",
    role: "Cluster Post",
    status: "Published",
    wordCount: 760,
    publishedUrl: "https://example.com/blog/realtor-personal-brand-photos",
    lastRefreshed: null,
    gbp: "2026-06-07",
  }),
  post({
    id: "demo-7",
    title: "Personal branding photography for consultants and coaches",
    slug: "personal-branding-consultants-coaches",
    dateWritten: "2026-06-02",
    topic: "personal branding consultants coaches",
    city: "Prairie Village",
    pillar: "Personal Branding Photography Kansas City",
    role: "Cluster Post",
    status: "Published",
    wordCount: 710,
    publishedUrl:
      "https://example.com/blog/personal-branding-consultants-coaches",
    lastRefreshed: null,
  }),
  post({
    id: "demo-8",
    title: "What to wear for a personal branding session",
    slug: "personal-branding-what-to-wear",
    dateWritten: "2026-06-16",
    topic: "personal branding what to wear",
    city: "Lenexa",
    pillar: "Personal Branding Photography Kansas City",
    role: "Cluster Post",
    status: "Draft",
    wordCount: 540,
    publishedUrl: null,
    lastRefreshed: null,
  }),
  post({
    id: "demo-9",
    title:
      "Corporate Team Headshots in Kansas City: The Complete Guide for HR and Office Managers",
    slug: "corporate-team-headshots-kc-guide",
    dateWritten: "2026-02-17",
    topic: "corporate team headshots Kansas City",
    city: "Overland Park",
    pillar: "Corporate Team Headshots Kansas City Metro",
    role: "Pillar Page",
    status: "Published",
    wordCount: 2140,
    publishedUrl: "https://example.com/blog/corporate-team-headshots-kc-guide",
    lastRefreshed: "2026-05-30",
    gbp: "2026-05-30",
  }),
  post({
    id: "demo-10",
    title: "How to plan a team headshot day without losing a morning",
    slug: "team-headshot-day-planning",
    dateWritten: "2026-06-09",
    topic: "team headshot day planning",
    city: "Overland Park",
    pillar: "Corporate Team Headshots Kansas City Metro",
    role: "Cluster Post",
    status: "Published",
    wordCount: 780,
    publishedUrl: "https://example.com/blog/team-headshot-day-planning",
    lastRefreshed: null,
  }),
  post({
    id: "demo-11",
    title: "On-location headshots for law offices: what to expect",
    slug: "on-location-headshots-law-offices",
    dateWritten: "2026-06-23",
    topic: "on-location headshots law offices",
    city: "Kansas City MO",
    pillar:
      "On-Location Headshots for Law Offices Small Businesses and Financial Institutions",
    role: "Cluster Post",
    status: "Draft",
    wordCount: 640,
    publishedUrl: null,
    lastRefreshed: null,
  }),
  post({
    id: "demo-12",
    title:
      "On-location headshots for financial advisors: compliance and confidence",
    slug: "on-location-headshots-financial-advisors",
    dateWritten: "2026-07-01",
    topic: "on-location headshots financial advisors",
    city: "Overland Park",
    pillar:
      "On-Location Headshots for Law Offices Small Businesses and Financial Institutions",
    role: "Cluster Post",
    status: "Planned",
    wordCount: null,
    publishedUrl: null,
    lastRefreshed: null,
  }),
  post({
    id: "demo-13",
    title: "Why this studio only books one client per shoot slot",
    slug: "why-one-photographer-per-shoot",
    dateWritten: "2026-04-06",
    topic: "exclusive photographer model",
    city: "Olathe",
    pillar: null,
    role: "Standalone",
    status: "Published",
    wordCount: 690,
    publishedUrl: "https://example.com/blog/why-one-photographer-per-shoot",
    lastRefreshed: null,
  }),
];

export const DEMO_TRACKER_DATA: TrackerData = {
  posts: DEMO_POSTS,
  hasGbpField: true,
};

export const DEMO_PILLARS = [
  "Studio Headshots Kansas City Area",
  "Personal Branding Photography Kansas City",
  "Corporate Team Headshots Kansas City Metro",
  "On-Location Headshots for Law Offices Small Businesses and Financial Institutions",
  "Conference and Convention Headshots",
];
